
import Header from './Components/Header/page';
import Footer from './Components/Footer/page';
import ThemeClient from './_app';
import type { Metadata } from 'next'
import { CSSReset } from '@chakra-ui/react';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeClient >
          <CSSReset/>
          <Header></Header>
          {children}
          <Footer></Footer>
        </ThemeClient>
      </body>
    </html>
  );
}